name: i3 AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/14 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |
        sudo apt update
        sudo apt install libev-dev libxkbcommon-dev libpango1.0-dev libcurl4-openssl-dev libxkbcommon-x11-dev libpango1.0-dev libpangocairo-1.0-0 desktop-file-utils
        sudo apt install libfuse2 gcc xsltproc autopoint libcairo2-dev xcb-proto libnl-genl-3-dev libxcb-composite0-dev libxcb-xrm-dev libxcb1-dev
        sudo apt install libuv1-dev pkg-config libxcb-cursor-dev libxcb-util-dev python3-pip libxcb-randr0-dev libxcb-util0-dev libcurlpp-dev libxcb-ewmh2 
        sudo pip3 install packaging meson
        sudo apt install libxcb-xkb-dev i3-wm libjsoncpp-dev libxcb-image0-dev libmpdclient-dev libxcb-icccm4-dev libalsaplayer-dev libalsaplayer0
        sudo apt install libncursesw5-dev autotools-dev autoconf automake build-essential ninja-build libxcb-ewmh-dev python3-xcbgen libpulse-dev
        sudo apt install libxcb-keysyms1-dev libmpdclient2 libxcb-xinerama0-dev libasound2-dev libiw-dev libyajl-dev libstartup-notification0-dev
        wget https://raw.githubusercontent.com/Samueru-sama/i3-AppImage/main/i3-AppImage-patched.sh
        wget https://raw.githubusercontent.com/Samueru-sama/i3-AppImage/main/i3-AppImage-git.sh
        chmod a+x ./i3-AppImage*.sh
        ./i3-AppImage-patched.sh
        ./i3-AppImage-git.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: i3-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: i3-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
